[build]
command = "pnpm build"
publish = "build/web"
functions = "netlify/deploy-functions"

[functions]
node_bundler = "esbuild"

[dev]
command = "pnpm vite --host 127.0.0.1"
targetPort = 5173
port = 8888
