"""Offline ``product-kit@1`` authoring contract."""

from .pack import write_product_kit_pack
from .schema import (
    AssetReference,
    Bounds,
    Certification,
    CompatibilityProfile,
    Component,
    Fragment,
    GridComponentFrame,
    GridMountFrame,
    GripComponentFrame,
    GripMountFrame,
    Kit,
    Point,
    ProductKitCatalogue,
    ProductKitCatalogueAssetRecord,
    ProductKitCatalogueContext,
    RasterFrame,
    SocketComponentFrame,
    SocketMountFrame,
    TransformConstraints,
    canonical_json_bytes,
    parse_product_kit_catalogue,
    validate_product_kit_catalogue,
)

__all__ = [
    "AssetReference",
    "Bounds",
    "Certification",
    "CompatibilityProfile",
    "Component",
    "Fragment",
    "GridComponentFrame",
    "GridMountFrame",
    "GripComponentFrame",
    "GripMountFrame",
    "Kit",
    "Point",
    "ProductKitCatalogue",
    "ProductKitCatalogueAssetRecord",
    "ProductKitCatalogueContext",
    "RasterFrame",
    "SocketComponentFrame",
    "SocketMountFrame",
    "TransformConstraints",
    "canonical_json_bytes",
    "parse_product_kit_catalogue",
    "validate_product_kit_catalogue",
    "write_product_kit_pack",
]
